"""Add completed to tasks and make names and titles non-nullable

Revision ID: a48e9d39ce1a
Revises: 2058103f38f8
Create Date: 2024-02-14 16:01:51.852114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48e9d39ce1a'
down_revision: Union[str, None] = '2058103f38f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=False))
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tasks', 'completed')
    op.alter_column('lists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
